version: '3.9'
#الإصدار 3.9 هو الأكثر شيوعًا ويدعم أغلب ميزات Docker الحديثة.
services:
  app:
    build: 
      context: .
      args:
        - name=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app #الحاوية
    command: >  
      sh -c "python manage.py runserver 0.0.0.0:8000"


#هذا القسم يحتوي على جميع الخدمات (containers) التي سيقوم Docker بتشغيلها.
#هنا لديك خدمة واحدة فقط: app

#استخدم Dockerfile الموجود في نفس المجلد الحالي

#هذا المجلد (.) هو سياق البناء الذي يتم منه نسخ الملفات إلى داخل الـ container

#بمعنى: Docker سيبني صورة جديدة من Dockerfile الموجود بجانب docker-compose.

#Host (جهازك): ports

#ما هدف هذا الـ volume؟

#هو ربط مجلد المشروع الخاص بك داخل جهازك (host) بالمجلد داخل container.

#الميزة:

#عندما تغيّر كود Django على جهازك → التغيير يظهر فورًا داخل container بدون إعادة بناء الصورة.

#وهذا ما نحتاجه أثناء التطوير.

#command 
#sh -c تعني "شغّل أمرًا داخل shell"

#الأمر هو تشغيل Django server

#runserver 0.0.0.0:8000 يجعل السيرفر يستقبل اتصالات من أي عنوان، وليس فقط localhost داخل container

#بدونه لن تستطيع الوصول للسيرفر من جهازك.